### ISSUE TITLE
Goal v1.0.1 not compatible with Ecto v3.12.1

### ISSUE THREAD

**Issue by boon-wego** [martinthenth/goal#101]
When you use `enum` validation (https://github.com/martinthenth/goal?tab=readme-ov-file#available-validations). You will get an error `** (FunctionClauseError) no function clause matching in Ecto.Type.cast_fun/1`

**Comment by martinthenth** [comment]
Thanks for the report. I'll take a look at the proposed fix by @deolivtiago
