### ISSUE TITLE
Bug: Regression with unspecified map fields

### ISSUE THREAD

**Issue by Miradorn** [martinthenth/goal#112]
Hey there!
I've been trying to update Goal from 0.3.3 to 1.0.1 and many of our schemas break.

They look like:
```
defparams :body do
      ...
      optional(:custom_fields, :map)
end
```
where `custom_fields` should be allowed to include anything.
This worked before, but after the update when validating the map is stripped of all fields 😢 

I can't find anything in the changelog about this, so I guess this is an unwanted change?

Thanks for any help!

**Comment by martinthenth** [comment]
Hi! Thank you for the bug report. You're right, there was a regression introduced in `v1.0.0`. I published the fix on hex.pm just now. Version `v1.1.1` should work correctly.

**Comment by Miradorn** [comment]
thanks!
