### ISSUE TITLE
Support {:array, type} with :rules for the inner type

### ISSUE THREAD

**Issue by LukasKnuth** [martinthenth/goal#49]
Currently, I can do this:

```elixir
defparams :update do
  required :options, {:array, :string}
end
```

This will validate that the values inside the `:options` array are strings. I'd like to propose the following notation:

```elixir
defparams :update do
  required :options, {:array, :string}, rules: [min: 1, trim: true]
```

This would be allowed for the inner types `string`, `integer`, `float`, `decimal`, `boolean`, `date`, and `time`. Not sure if it's possible/useful for `enum`. For maps, we already have existing notation.

It runs the validations available for the inner type on each value _inside_ the array and adds the errors accordingly.

Ideally, this can be implemented by just using the inner type, validating it as if it where a top-level parameter and merging the result back into the nested array.

Any input/considerations/feelings towards this proposal? I'll go ahead and hack at it a bit, see what I come up with.

**Comment by LukasKnuth** [comment]
@martinthenth ping.

**Comment by martinthenth** [comment]
Interesting! I like it. I was thinking on the syntax and how it could evolve, maybe it would be possible to forego `rules` and define the schema like with basic fields?

```elixir
defparams :update do
  required :options, {:array, :string}, min: 1, trim: true
end
```

Later, it could then allow `length`, `min_length`, and `max_length` for rules on the array 🤔 WDYT?

**Comment by LukasKnuth** [comment]
I feel like it's important that it be clear which of the rules are applied to the item and which of them are applied to the array. 

On option I would like to propose is keeping the rule of "the rules next to the entry apply to the entry only" and implement the item rules in a do block, like for properties?

```elixir
defparams :update do
  required :options, {:array, :string}, min: 1, max: 5 do
    item min: 1, trim: true
  end
end
```

perhaps even:

```elixir
defparams :update do
  required :options, :array, min: 1, max: 5 do
    item :string, min: 1, trim: true
  end
end
```

I'm not sure how involved that would be with the macro parsing logic, but this is a little clearer. The only problem I see is that it's not immediately obvious that `item` can only be used inside array blocks.

**Comment by martinthenth** [comment]
After some thinking, I agree there should be some sort of differentiation. `:rules` as proposed seems like a good choice

**Comment by martinthenth** [comment]
Well done on implementing this feature! 👏🏻 

Feature was added in https://github.com/martinthenth/goal/pull/50
