### ISSUE TITLE
Add `unique` transform for Arrays

### ISSUE THREAD

**Issue by LukasKnuth** [martinthenth/goal#51]
This would work similar to how `trim` works on strings. It doesn't really validate anything but modifies the input value by removing any duplicate array items.

```elixir
required :options, {:array, :string}, unique: true
```

I'd expect this to work in order with the other defined validations, so defining `rules: [trim: true], unique: true` would first trim all items in the array and _then_ remove any repeated items.

What do you think?

**Comment by LukasKnuth** [comment]
I have a first implementation ready that works as described above.

The only change that's somewhat interesting is changing the order of `validate_nested_fields/3` and `validate_basic_fields/2` inside of `build_changeset/2`. This is to allow the second behavior I described above. So far, the only test failures I see following that change is the order of errors in changesets.

Once #49 is merged and `main` is clean, I'll rebase the changes on it and show you the implementation. Maybe we can include it in the next release also :)

**Comment by martinthenth** [comment]
I'm wonder whether guaranteeing the uniqueness of the parameters should be the client's responsibility 🤔 Also, after validating the parameters the business logic could dedup values

**Comment by LukasKnuth** [comment]
I see your point.

Since the changes I'm proposing would be somewhat large to make this possible in the first place, I don't think it's worth it right now.
