### ISSUE TITLE
Allow specifying any regex to `format`

### ISSUE THREAD

**Issue by LukasKnuth** [martinthenth/goal#52]
We'd still keep the pre-filled format options (like email, uuid, etz), but we'd also allow just giving any `%Regex{}` to the `:format` validation.

This allows some more flexibility:

```elixir
required :id, :string, trim: true, format: ~r/^[a-z0-9-]+$/i
```

---

I have a working version that I can create a PR for as soon as main is clean again after #50

Thoughts?

**Comment by martinthenth** [comment]
Looks useful and it makes sense to enable additional customization since there's `uuid`, `email` and `password` already. I also like that it will be a `Regex` so it could some e.g. from a module attribute or application config.

**Comment by martinthenth** [comment]
This feature was added by @LukasKnuth in https://github.com/martinthenth/goal/pull/53 🎉
