### ISSUE TITLE
Support for flexible schema

### ISSUE THREAD

**Issue by laiboonh** [martinthenth/goal#62]
Would this be able to support use case like:

if param foo is true, we require param bar to be given (required) if not bar is not required

**Comment by martinthenth** [comment]
If they are adjacent fields, then not out of the box I think. If the toggling field is a map and the dependent fields are keys in the map then yes it it supported. 

Assuming it's the first: I remember a similar use-case I had a long time ago, and back then we went with defining multiple schemas and selecting the schema in the controller.

Something like this:

```elixir
def MyController do
  def create(conn, params) do
    action = if Map.get(params, :toggle), do: :action1, else: :action2

    with {:ok, attrs} <- MySchema.validate(action) do
      ...
    end
  end
end

def MySchema do
  defparams :action1 do
    ...
  end

  defparams :action2 do
    ...
  end
end
```
