### ISSUE TITLE
Support for passing a function or constant to enum values

### ISSUE THREAD

**Issue by hamptokr** [martinthenth/goal#64]
First off, thanks so much for a wonderful library! We are currently using `goal` to validate params before sending to a 3rd party API and it's working great! One pain point we've run into is it's currently impossible to share enums across modules. Here's a minimal example that will error:

```elixir
defmodule MyValidation do
  use Goal

  defp statuses, do: ["draft", "pending", "done"]

  defparams :index do
    optional :status, :enum, values: statuses()
  end

  defparams :update do
    optional :status, :enum, values: statuses()
  end
end
```

If you try to do the above, once the macro is expanded, you won't get the result of `statuses()` as a list of atoms. Instead it gets expanded to `status: [type: :enum, values: {:{}, [], [:statuses, [line: 4], []]}]`.

The problem code seems to be here where the `block` passed to `generate_schema/1` has been given a function tuple in place of `statuses()` instead of the result of a call to the function.

```elixir
def schema(unquote(name)) do
  unquote(block |> generate_schema() |> Macro.escape())
end
```

Within `generate_schema/1` I've tried a couple different things without luck, for example calling `apply` on the function tuple with `__CALLER__` when `values` appears in the `options` provided. Just trying to get the function evaluated to a list of strings before later getting passed to `get_types/1` and `String.to_atom/1` which does not succeed.

```elixir
  defp get_types(schema) do
    Enum.reduce(schema, %{}, fn {field, rules}, acc ->
      case Keyword.get(rules, :type, :any) do
        :enum ->
          values =
            rules
            |> Keyword.get(:values, [])
            |> Enum.map(&String.to_atom/1)

          Map.put(acc, field, {:parameterized, Ecto.Enum, Ecto.Enum.init(values: values)})

    # ...
  end
```

I'm a little out of my depth with the macros here, but any guidance or ideas would be much appreciated! Or if you have a quick solution/workaround, even better! Thanks in advance for your time!

**Comment by hamptokr** [comment]
I gave that solution a try but it seems `Macro.expand` just gives back the same AST block rather than the evaluated list. My hunch is that it's this problem: https://stackoverflow.com/questions/43972492/how-to-get-an-unquoted-expanded-parameter-s-value-inside-a-macro

But I do wonder how `ecto` gets around this 🤔 

The AST that's left in place also doesn't have enough information to call `apply` at runtime as it's just `{:{}, [], [:statuses, [line: 4], []]}`.

However it got me thinking, at compilation time in the macro I can get the module from `__CALLER__`, inject it into the AST and then at runtime we can resolve that in `get_types`. It's very rough and only works for _public_ functions not `@constants`: https://github.com/hamptokr/goal/commit/faeb460ee0bdedb7412ac0383033d3ddf7da85ed

This is probably way overcomplicating things 😅

**Comment by lucca65** [comment]
Just want to let you guys know that I came across this exact issue today while validating my params. Took me a while to realize the macro wasn't processing my `~w()` sigil. Is there any workaround?

**Comment by martinthenth** [comment]
Hey there! I think I have found a working solution to support passing module attributes to the schema. I'll include it in [version 1.0.0](https://github.com/martinthenth/goal/pull/93) 🙂 

I did a quick check with `Ecto.Schema`, and it looks like Ecto doesn't support passing functions to schemas 🤔 I think module attributes should be a suitable replacement

**Comment by martinthenth** [comment]
Released in https://hex.pm/packages/goal

**Comment by lucca65** [comment]
Congratulations on the 1.0 🎉
