### ISSUE TITLE
Issue with negative numbers

### ISSUE THREAD

**Issue by zhora-nersisyan** [martinthenth/goal#87]
Whenever I try to use a negative number of any kind (integer, decimal, float) i get an `ArgumentError`.
For example:
```
 required(:longitude, :float,
      min: -180.0,
      max: 180.0
    )
```
Fails with:
```
** (ArgumentError) expected option `greater_than_or_equal_to` to be a decimal, integer, or float, got: {:-, [line: 33, column: 12], [180.0]}
```

**Comment by martinthenth** [comment]
Hey! Thanks for your report. @Joraeuw prepared a fix for this issue in https://github.com/martinthenth/goal/pull/88. I'll prepare a bug fix release soon and let you know.

**Comment by martinthenth** [comment]
I published a new version on hex.pm that includes the fix for this issue: https://hex.pm/packages/goal/0.3.3
